name: PlayerProfiles
version: 1.0
api-version: 1.16
author: ForeverInColor
main: me.foreverincolor.playerprofiles.Main

depend: [PlaceholderAPI]

commands:
  profile:
    description: view and manage profile
    usage: /profile <playername | set age | set discord>